defaults:
  - /connector@connector: retro_act
  - _self_

connector:
  variant: random
  annotation_control_fpath: annotations/RetroAct_v0.1_control_GenieRedux-G-50_sublist.csv
  generator_config:
    n_instances: 1
    n_sessions: 100
    n_steps_max: 500
    n_workers: 10
    output_mode: frame

dname: g50
