defaults:
  - /connector@connector: retro_act
  - _self_

connector:
  variant: random
  limit_games: 200
  annotation_control_fpath: null
  generator_config:
    n_instances: 1
    n_sessions: 50
    n_steps_max: 500
    n_workers: 10
    output_mode: frame

dname: g200
