defaults:
  - /connector@connector: coinrun
  - _self_

connector:
  generator_config:
    n_instances: 1000
    n_sessions: 1
    n_steps_max: 500
    n_workers: 48
    output_mode: frame

dname: test
