defaults:
  - /connector@connector: coinrun
  - _self_

connector:
  agent_type: random
  generator_config:
    n_instances: 10000
    n_sessions: 1
    n_steps_max: 500
    n_workers: 48
    output_mode: frame
