# @package _global_

defaults:
  - default
  - /tokenizer/tokenizer
  - /lam/lam
  - /dynamics/dynamics
  - _self_

model: genie_redux

train:
  dataset_root_dpath: "data_generation/datasets"
  dataset_name: "retro_act_v0.0.0"
  wandb_name: "genie_redux"
  batch_size: 3
  grad_accum: 4
  n_data_workers: 46
  n_total_samples: 50
  n_envs: 0
  max_valid_size: 50
  use_decoder_loss: false

dynamics:
  max_seq_len: 8000

tokenizer_fpath: ${train.save_root_dpath}/tokenizer/tokenizer/model-150000.pt

eval:
  dataset_root_dpath: ${train.dataset_root_dpath}
  dataset_name: ${train.dataset_name}
  model_fpath: ${train.save_root_dpath}/${model}/${train.wandb_name}/model-150000.pt
  eval_control: "yes"
