defaults:
  - default
  - /tokenizer/tokenizer.yaml
  - _self_

model: tokenizer
mode: train

train:
  dataset_root_dpath: "data_generation/datasets"
  dataset_name: "retro_gym_v0.0.0"
  wandb_name: "tokenizer"
  batch_size: 7
  batch_size_val: 20
  grad_accum: 4
  n_data_workers: 46
  n_total_samples: 50
  n_envs: 10
  max_valid_size: 50