# @package _global_

defaults:
  - default
  - /tokenizer/tokenizer.yaml
  - _self_

model: tokenizer

train:
  dataset_root_dpath: "data_generation/datasets"
  dataset_name: "retro_act_v0.0.0_auto_explore_smb"
  wandb_name: "tokenizer_ft_smb"
  batch_size: 7
  batch_size_val: 20
  grad_accum: 4
  n_data_workers: 46
  n_total_samples: 50
  n_envs: 0
  max_valid_size: 50
  num_train_steps: 15000

tokenizer_fpath: ${train.save_root_dpath}/tokenizer/tokenizer/model-150000.pt